### Convert IMAE_NL
POST http://localhost:5231/api/historical-pricing/instruments/convert
Content-type: application/json

{
  "instrument": "IMAE_NL",
  "currency": "RON",
  "dates": [
    "2023-01-01",
    "2023-05-07",
    "2024-02-03",
    "2024-04-23"
  ]
}

### Convert Goldman Sachs Romania Equity
POST http://localhost:5231/api/historical-pricing/instruments/convert
Content-type: application/json

{
  "instrument": "GOLDMAN_SACHS_RO_EQ",
  "currency": "EUR",
  "dates": [
    "2023-01-01",
    "2023-05-07",
    "2024-02-03",
    "2024-03-05"
  ]
}

### Convert BT Maxim
POST http://localhost:5231/api/historical-pricing/instruments/convert
Content-type: application/json

{
  "instrument": "BT_ENERGY",
  "currency": "EUR",
  "dates": [
    "2023-01-01",
    "2023-05-07",
    "2024-02-03",
    "2024-03-05"
  ]
}

### Convert RON to EUR
POST http://localhost:5231/api/historical-pricing/currencies/convert
Content-type: application/json

{
  "sourceCurrency": "RON",
  "targetCurrency": "EUR",
  "dates": [
    "2019-01-01",
    "2019-04-01",
    "2019-04-30",
    "2020-01-01"
  ]
}

### Convert EUR to RON
POST http://localhost:5231/api/historical-pricing/currencies/convert
Content-type: application/json

{
  "sourceCurrency": "EUR",
  "targetCurrency": "RON",
  "dates": [
    "2019-01-01",
    "2019-04-01",
    "2019-04-30",
    "2020-01-01"
  ]
}
