### Get Users
GET {{user_host}}/funds-api/user/v1/users

### Get User by id
GET {{user_host}}/funds-api/user/v1/users/{{user-id}}

### Get User by username
GET {{user_host}}/funds-api/user/v1/users/username/{{username}}

> {%
    client.global.set("user-id", response.body["id"]);
%}

### Create User
POST {{user_host}}/funds-api/user/v1/users
Content-Type: application/json

{
  "username": "user"
}
> {%
    client.global.set("user-id", response.body["id"]);
%}

### Delete User
DELETE {{user_host}}/funds-api/user/v1/users/{{user-id}}
