ktor:
  application:
    id: "funds::fund-service"
    modules:
      - ro.jf.funds.fund.service.FundServiceApplicationKt.module
  deployment:
    port: 5253
environment: "$ENVIRONMENT:local"
database:
  url: "$DATABASE_URL:jdbc:postgresql://localhost:5438/ff_fund"
  user: postgres
  password: pass
kafka:
  bootstrap-servers: "$KAFKA_BOOTSTRAP_SERVERS:localhost:29092"
  group-id: fund-service
  client-id: fund-service
integration:
  account-service:
    base-url: "$ACCOUNT_BASE_URL:http://localhost:5211"
observability:
  enabled: true
  otel-collector:
    grpc-endpoint: "$OTEL_COLLECTOR_GRPC_ENDPOINT:http://localhost:4317/v1/traces"