ktor:
  application:
    modules:
      - ro.jf.funds.fund.service.FundServiceApplicationKt.module
  deployment:
    port: 5253
database:
  url: "$DATABASE_URL:jdbc:postgresql://localhost:5438/ff_fund"
  user: postgres
  password: pass
kafka:
  bootstrapServers: "$KAFKA_BOOTSTRAP_SERVERS:localhost:9092"
  groupId: fund-service
  clientId: fund-service

integration:
  account-service:
    base-url: "$ACCOUNT_BASE_URL:http://localhost:5211"
