ktor:
  application:
    modules:
      - ro.jf.funds.account.service.AccountServiceApplicationKt.module
  deployment:
    port: 5211
database:
  url: "$DATABASE_URL:jdbc:postgresql://localhost:5438/ff_account"
  user: postgres
  password: pass
