ktor:
  application:
    id: "funds::account-service"
    modules:
      - ro.jf.funds.account.service.AccountServiceApplicationKt.module
  deployment:
    port: 5211
environment: "$ENVIRONMENT:local"
database:
  url: "$DATABASE_URL:jdbc:postgresql://localhost:5438/ff_account"
  user: postgres
  password: pass
kafka:
  bootstrap-servers: "$KAFKA_BOOTSTRAP_SERVERS:localhost:29092"
  group-id: account-service
  client-id: account-service
observability:
  enabled: true
  otel-collector:
    grpc-endpoint: "$OTEL_COLLECTOR_GRPC_ENDPOINT:http://localhost:4317/v1/traces"
