### https://currencybeacon.com/api-documentation

### Convert EUR -> RON
GET	https://api.currencybeacon.com/v1/historical?base=EUR&symbols=RON&date=2021-02-28&api_key=lD4Xtx1DjrCjfD7ogW49dlqnv778aYWH

### Convert RON -> EUR
GET	https://api.currencybeacon.com/v1/historical?base=EUR&symbols=RON&date=2022-06-25&api_key=lD4Xtx1DjrCjfD7ogW49dlqnv778aYWH

### Expired api key
GET	https://api.currencybeacon.com/v1/historical?base=EUR&symbols=RON&date=2021-02-28&api_key=BEUseQ6C0HKAKXOeA5dZzsxmXV8HuRbL

### Invalid api key
GET	https://api.currencybeacon.com/v1/historical?base=EUR&symbols=RON&date=2021-02-28&api_key=invalid
