ktor:
  application:
    modules:
      - ro.jf.funds.historicalpricing.service.HistoricalPricingApplicationKt.module
  deployment:
    port: 5231
database:
  url: "$DATABASE_URL:jdbc:postgresql://localhost:5438/bk_historical_pricing"
  user: postgres
  password: pass
