ktor:
  application:
    id: "funds::historical-pricing-service"
    modules:
      - ro.jf.funds.historicalpricing.service.HistoricalPricingApplicationKt.module
  deployment:
    port: 5231
database:
  url: "$DATABASE_URL:jdbc:postgresql://localhost:5438/bk_historical_pricing"
  user: postgres
  password: pass
observability:
  enabled: true
  otel-collector:
    grpc-endpoint: "$OTEL_COLLECTOR_GRPC_ENDPOINT:http://localhost:4317/v1/traces"
