/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.3/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.jetbrains.kotlin.jvm") version "2.1.20"
    id("org.jetbrains.kotlin.plugin.serialization") version "2.1.20"
    `maven-publish`
    `java-library`
}

group = "ro.jf.funds"
version = "1.0.0"

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    implementation("ro.jf.funds:user-sdk:1.0.0")
    implementation("ro.jf.funds:fund-sdk:1.0.0")
    implementation("ro.jf.funds:import-sdk:1.0.0")
    implementation("ro.jf.funds:reporting-sdk:1.0.0")
    implementation("org.jetbrains.kotlinx:kandy-lets-plot:0.8.0")
    implementation("org.jetbrains.kotlinx:kandy-api:0.8.0")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.8.1")
    implementation("org.jetbrains.kotlinx:kotlinx-datetime:0.6.0")
    implementation("com.charleskorn.kaml:kaml:0.83.0")
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

publishing {
    publications {
        create<MavenPublication>("mavenKotlin") {
            from(components["kotlin"])

            groupId = group.toString()
            artifactId = "funds-notebook-client"
            version = rootProject.version.toString()
        }
    }
}

tasks.register("installLocal") {
    group = "build"
    description = "Build the artifact, publish it to local maven"

    dependsOn("build", "publishToMavenLocal")
}
