ktor:
  application:
    modules:
      - ro.jf.bk.fund.service.FundServiceApplicationKt.module
  deployment:
    port: 5253
database:
  url: "$DATABASE_URL:jdbc:postgresql://localhost:5438/ff_fund"
  user: postgres
  password: pass
integration:
  account-service:
    base-url: "$ACCOUNT_BASE_URL:http://localhost:5211"
