ktor:
  application:
    modules:
      - ro.jf.bk.user.service.UserServiceApplicationKt.module
  deployment:
    port: 5247
database:
  url: "$DATABASE_URL:jdbc:postgresql://localhost:5438/ff_user"
  user: postgres
  password: pass
