ktor:
    application:
        modules:
            - ro.jf.finance.historicalpricing.service.HistoricalPricingApplicationKt.module
    deployment:
        port: 5231
database:
    url: "jdbc:postgresql://localhost:5438/bk_historical_pricing"
    user: postgres
    password: pass