ktor:
  application:
    modules:
      - ro.jf.funds.reporting.service.ReportingServiceApplicationKt.module
  deployment:
    port: 5212
environment: "$ENVIRONMENT:local"
integration:
  fund-service:
    base-url: "$FUND_BASE_URL:http://localhost:5253"
kafka:
  bootstrap-servers: "$KAFKA_BOOTSTRAP_SERVERS:localhost:29092"
  group-id: reporting-service
  client-id: reporting-service
database:
  url: "$DATABASE_URL:jdbc:postgresql://localhost:5438/ff_reporting"
  user: postgres
  password: pass
