ktor:
  application:
    id: "funds::import-service"
    modules:
      - ro.jf.funds.importer.service.ImportServiceApplicationKt.module
  deployment:
    port: 5207
environment: "$ENVIRONMENT:local"
database:
  url: "$DATABASE_URL:jdbc:postgresql://localhost:5438/ff_import"
  user: postgres
  password: pass
  connection-pool-size: "$DATABASE_CONNECTION_POOL_SIZE:10"
kafka:
  bootstrap-servers: "$KAFKA_BOOTSTRAP_SERVERS:localhost:29092"
  group-id: import-service
  client-id: import-service
integration:
  account-service:
    base-url: "$ACCOUNT_BASE_URL:http://localhost:5211"
  fund-service:
    base-url: "$FUND_BASE_URL:http://localhost:5253"
  historical-pricing-service:
    base-url: "$HISTORICAL_PRICING_BASE_URL:http://localhost:5231"
observability:
  enabled: true
  otel-collector:
    grpc-endpoint: "$OTEL_COLLECTOR_GRPC_ENDPOINT:http://localhost:4317/v1/traces"
